### ISSUE TITLE
Doc comments for behavior and function edit files

### ISSUE THREAD

**Issue by leeyspaul** [scottgigante/korean-support#16]
### Request

It would be helpful to have doc comments added for these functions as it seems this is where the bulk for the functionality lives. 

## Files

- [edit_behavior.py](https://github.com/scottgigante/korean-support/blob/master/korean/edit_behavior.py)
- [edit_functions.py](https://github.com/scottgigante/korean-support/blob/master/korean/edit_functions.py)

## Tasks
- [ ] Remove references from chinese-support plugin
- [ ] Add doc comments for behavior
- [ ] Add doc comments for functions

**Comment by leeyspaul** [comment]
added thought: I think this would be a great first issue for first time contributors and could use those labels!
